### ISSUE TITLE
Is jQuery needed

### ISSUE THREAD

**Issue by grgur** [RoboDomo/react-client#32]
jQuery is a dependency. Can we get rid of it?

**Comment by mschwartz** [comment]
react-bootstrap doesn’t depend on it.  It’s likely the 3rd party react-nest-thermostat component.

Our choices then would be to hack on that component or not use it.  If we don’t use it, we have to redesign the thermostat displays.

Which is the better use of our time?

**Comment by grgur** [comment]
We definitely don't refactor anything. I saw it in dependencies, but I couldn't find a reference to it. I wonder if Nest will work if you remove jquery. Mind checking?

**Comment by mschwartz** [comment]
jQuery is a dependency of bootstrap, which we don't use directly.  I don't think it's every loaded into the client, just yanked in due to the dependency madness of the world of packages.

I removed it from package.json and did yarn install:

![2019-06-26 at 8 16 AM](https://user-images.githubusercontent.com/329637/60192513-ce40b780-97ea-11e9-853e-c756b5c2b2e0.png)

**Comment by mschwartz** [comment]
https://react-bootstrap.github.io/

Rebuilt with React
React bootstrap replaces the Bootstrap javascript. Each component has been built from scratch as a true React component, without unneeded dependencies like jQuery.

**Comment by mschwartz** [comment]
https://react-bootstrap.github.io/getting-started/introduction

![2019-06-26 at 8 18 AM](https://user-images.githubusercontent.com/329637/60192641-0c3ddb80-97eb-11e9-959c-12a764316507.png)

So bootstrap is required just for the CSS.  The jQuery dependency is not.
